use_frameworks!
platform :ios, '9.0'

target 'MultipageForm_Example' do
  pod 'MultipageForm', :path => '../'

  target 'MultipageForm_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
